### ISSUE TITLE
Location filtering with FusedLocationProvider

### ISSUE THREAD

**Issue by svvashishtha** [maddevsio/mad-location-manager#105]
@Lezh1k I have integrated FusedLocationProvider in KalmanFilteringSerivce. Before I open a PR I wanted to know if there is any reason that it has not been done already?

**Comment by Lezh1k** [comment]
Sure :) 
We didn't have google play services on those old phones :)

**Comment by svvashishtha** [comment]
I will open my PR after some more testing then.

**Comment by Lezh1k** [comment]
Awesome :)

**Comment by svvashishtha** [comment]
https://github.com/maddevsio/mad-location-manager/pull/106

**Comment by svvashishtha** [comment]
Closing this since PR is merged.
