### ISSUE TITLE
Sample not working

### ISSUE THREAD

**Issue by al-t** [maddevsio/mad-location-manager#11]
I have the same issue as described here - https://github.com/maddevsio/mad-location-manager/issues/2
I cloned the repository, built the apk and started it on the phone, but it doesn’t seem to work ok.
See the screenshots of what happens when I press on buttons in the app:
![2](https://user-images.githubusercontent.com/2982447/40576504-65ce6c5a-6100-11e8-9d22-c5ce4570cc09.png)
![1](https://user-images.githubusercontent.com/2982447/40576505-65ed233e-6100-11e8-8b64-0e63ddf8d859.png)

I open the log file in SendDataCollector folder and there I can see a whole bunch of data, like that:
```
1527313200064|I|X-LOG|31007242 GPS : pos lat=55,593639, lon=37,478290, alt=217,394154, hdop=8,000000, speed=16,755537, bearing=21,427261, sa=0,800000
1527313200065|I|X-LOG|01007242 KalmanAlloc : lon=37,478290, lat=55,593639, speed=16,755537, course=21,427261, m_accDev=0,100000, posDev=8,000000
1527313202025|I|X-LOG|31009225 GPS : pos lat=55,593906, lon=37,478476, alt=217,249434, hdop=6,000000, speed=16,708115, bearing=21,522673, sa=0,600000
1527313202135|I|X-LOG|21009225 KalmanUpdate : pos lon=37,478476, lat=55,593906, xVel=-14,907940, yVel=7,544164, posErr=6,000000, velErr=0,600000
1527313204035|I|X-LOG|31011234 GPS : pos lat=55,594177, lon=37,478662, alt=216,945878, hdop=6,000000, speed=16,529324, bearing=21,998478, sa=0,600000
1527313204138|I|X-LOG|21011234 KalmanUpdate : pos lon=37,478662, lat=55,594177, xVel=-16,528880, yVel=-0,121148, posErr=6,000000, velErr=0,600000
```
So, the app actually gets the location data but does not show anything on UI of the app (I thought there will be the track shown on the map).
Why doesn’t it show anything?

**Comment by Lezh1k** [comment]
Hello there :)
Seem's like something wrong with sensors : there is no any information about acceleration in logs. So could you check that application has rights to get data from linear accelerometer , magnetometer and gyroscope sensors?

**Comment by al-t** [comment]
Yes, thanks - you are quite right!
I checked for the sensors that I've got on the phone and found out that I have only TYPE_ACCELEROMETER sensor, but not TYPE_LINEAR_ACCELERATION (the types are taken from here - https://developer.android.com/guide/topics/sensors/sensors_motion ). Could the TYPE_ACCELEROMETER sensor be used instead of the TYPE_LINEAR_ACCELERATION sensor?
Also, there is no magnetometer or gyroscope sensors as well in the phone.
Which means - the phone is not suitable for the Mad Location Manager? 
Could you please write - what are the minimal requirements for using it?

**Comment by Lezh1k** [comment]
You don't have "TYPE_LINEAR_ACCELERATION" , right? That mean that you have really old phone :)) 
We use TYPE_LINEAR_ACCELERATION and TYPE_ROTATION_VECTOR. So there is a lot of work if your phone has not these sensors. 
We can use high-pass filter with usual TYPE_ACCELEROMETER. 
Also we can use Madgwick filter (as I wrote in (article)[https://blog.maddevs.io/reduce-gps-data-error-on-android-with-kalman-filter-and-accelerometer-43594faed19c]) or some good alternatives with older phones.

**Comment by spiritinlife** [comment]
Hey @Lezh1k i face the same issues with some old phones.
Is there any configurations with which i can use this phone 
https://www.devicespecifications.com/en/model/bd123fc8
It is a **Tp link neffos y50** with Proximity and Accelerometer sensor. 
I guess we are missing magnetometer  and gyroscope for TYPE_ROTATION_VECTOR?

> Could you please write - what are the minimal requirements for using it?

This would be very helpful and would avoid future issues on this subject.

Thank you for your awesome work 🖖

**Comment by Lezh1k** [comment]
@spiritinlife , @al-t 
Thank you for feedback. 
I'll add minimal requirements to readme.md.  

Right now these sensors should be available: 
TYPE_ROTATION_VECTOR, TYPE_LINEAR_ACCELERATION . 

It's possible to use just TYPE_ACCELEROMETER with high-pass filter. Also it's possible to use Madgwick filter instead of rotation vector, but gyroscope and magnetometer should be available in that case.

**Comment by al-t** [comment]
Thank you very much for you help!

You wrote that It is possible to use just TYPE_ACCELEROMETER with high-pass filter.
I'm considering adding such an option for the low-end phones segment. I gather, for that I need to filter out the acceleration due to gravity from sensors output and use the refined linear acceleration in Kaman filter as if it was received from TYPE_LINEAR_ACCELERATION sensor. But as I see it in onSensorChanged method of KalmanLocationService, the data is passed to SensorGpsDataItem along with magnetic declination, which I believe can not be obtained without magnetometer. Am I right? So, how can we actually use the Kalman filter with only a general accelerometer? Will it be possible to use your library with minor tweaks in it or it will be a whole new story?

**Comment by Lezh1k** [comment]
@al-t 
Hello. 
There is some misunderstanding here, my fault. Sorry for that. 
It's not possible to use just accelerometer. We need TYPE_ROTATION_VECTOR (it uses magnetometer and accelerometer as I understood from sources) OR we need accelerometer+magnetometer+gyroscope(optional) for Madgwick filter. 
These two ones are used for getting phone orientation. With phone orientation we can use accelerometer as INS. 

If you don't have these sensors (magnetometer at least) you can use GPS only based solutions, just using realtime geohash filter (class in current solution). It will remove "jumps" from route at least. Also you can use [this](https://github.com/andreynovikov/GeoTrackFilter) solution.

**Comment by al-t** [comment]
Great, thank you!
