### ISSUE TITLE
Calibration of sensors for Kalman filter

### ISSUE THREAD

**Issue by al-t** [maddevsio/mad-location-manager#13]
In the Sample application, there is a calibration button. Is that calibration required for getting the proper results? 
Should it be called somehow, when using the mad location manager in the app, before we register with ServicesHelper.addLocationServiceInterface(this) and subscribe to location updates?

**Comment by Lezh1k** [comment]
@al-t  Sorry for late answer. 
Yes, we can get sigmas from calibration step. But! In real car there are a lot of vibrations (because of engine). So it's better to use calibration step in car with turned on engine. 
I don't use it in real application, I use default value and it works for me :)
