### ISSUE TITLE
accelerometer

### ISSUE THREAD

**Issue by Begemot34** [maddevsio/mad-location-manager#14]
Hello, it lib look intersting, thank you!
Im confusing with use only TYPE_ACCELEROMETER in high-pass filter. Some device dont have gyroscopes and TYPE_ROTATION_VECTOR, TYPE_LINEAR_ACCELERATION not available...  What values of this sensors i must use in onSensorChanged?

**Comment by Lezh1k** [comment]
Hello :) 
Method won't work without those sensors, sorry. 
I mean you need at least magnetometer + accelerometer.
