### ISSUE TITLE
Тестирование на различных данных

### ISSUE THREAD

**Issue by YuriyRusinov** [maddevsio/mad-location-manager#19]
Здравствуйте !

Я занимаюсь фильтрацией звезд на треках автотранспорта, возможно ли Ваш пакет использовать для тестирования фильтрации на своих данных ?

**Comment by Lezh1k** [comment]
Добрый день. Спасибо за интерес к нашему проекту.
Если я правильно понял и звезда - это возникшая траектория водителя, когда он по факту стоял на месте (из-за "скачков"), то да, текущий пакет можно использовать для тестирования. 

Только нужно будет привести Ваши тестовые данные к формату, который "понимает" наше тестовое приложение, написанное на C++ (qt) . Ну или сразу использовать нашу библиотеку для сбора и проверки данных.

https://github.com/maddevsio/mad-location-manager/blob/master/C/src/SensorController.cpp  - здесь можно ознакомиться с форматом, который ждёт тестовое приложение.

**Comment by YuriyRusinov** [comment]
Здравствуйте !

У меня тут еще 1 вопрос появился, в случае когда наблюдениями являются широта, долгота, скорость и направление движения, каковы должны быть размерности матрицы эволюции системы, матрицы управления ? Cпасибо.

**Comment by Lezh1k** [comment]
Добрый вечер. 

Вы можете посмотреть пример в приложении Maps, написанном на С++ . Там есть вариант когда не используется скорость от GPS.  https://github.com/maddevsio/mad-location-manager/blob/master/C/src/GPSAccKalman.cpp . 

Однако для того, чтоб использовать скорость от GPS , нужно будет сделать так:
```
f->kf = KalmanFilterCreate(4, 4, 2);
```

Имейте в виду, что там нужно будет по другому инициализировать матрицы. 
Ну и результаты сразу становятся хуже , в случае потери связи с GPS . Так же есть проблема с тем, что сигму скорости получить можно в версиях API андроида не меньше 24.

**Comment by YuriyRusinov** [comment]
Здравствуйте !

Еще 1 вопрос возник, в Вашем проекте в вычислениях используются координаты (широта-долгота) или осуществляется пересчет в декартовы (X, Y) ?

**Comment by Lezh1k** [comment]
Широта долгота. :) Я их где-то обзываю X Y для удобства. Но на деле кажется y - широта, а x - долгота. :)
