### ISSUE TITLE
Sample not working

### ISSUE THREAD

**Issue by ZaydelEduard** [maddevsio/mad-location-manager#2]
Where i can see documentation? Or working sample? For now, sample not detect location or anything, tested on Genymotion, and two real phones.

**Comment by Lezh1k** [comment]
@ZaydelEduard  hello. 
Documentation is here : https://github.com/maddevsio/mad-location-manager/wiki/HowTo-use-library . 
Sample application called "sensor data collector" is in repo too.

**Comment by ZaydelEduard** [comment]
Yep, i know about your sample application!
I cloned that, started - but as result - nothing.
No detected my real location, no tracked anything.

**Comment by Lezh1k** [comment]
Ok then, could you check GPS settings? I mean GPS should be enabled somewhere in settings (usual settings->location or settings->privacy->location).

**Comment by ZaydelEduard** [comment]
Yep, i turned on GPS on phone and Genymotion also. And have stable internet connection. Nothing changed

**Comment by Lezh1k** [comment]
So GPS enabled and used as location source (GPS used, not Wi-fi and mobile network) and nothing is happening. That's really strange, but I hope we will find the reason. 
Ok, could you check if log file exists? It should be located on your external storage -> SendorDataCollector folder.  
If yes - can you provide it?

**Comment by puzanov** [comment]
@ZaydelEduard ? any progress?

**Comment by puzanov** [comment]
Closing this issue. Will open when @ZaydelEduard will return.
