### ISSUE TITLE
Could not resolve library path

### ISSUE THREAD

**Issue by Gabriel0402** [maddevsio/mad-location-manager#26]
Built new app with the configure error:
Could not find method compile() for arguments [com.github.maddevsio:mad-location-manager:0.1.9] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by Lezh1k** [comment]
Hello. Try to change build file. Actual version of library is 13

**Comment by Lezh1k** [comment]
0.1.13 I mean

**Comment by Gabriel0402** [comment]
Still got the error: Could not find method compile() for arguments [com.github.maddevsio:mad-location-manager:0.1.13] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

Here's the build file:
buildscript {
    
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}


allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

dependencies {
    compile 'com.github.maddevsio:mad-location-manager:0.1.13'
}

But could build by importing the library:
settings: include ':app',':madlocationmanager'
build: api project(path: ':madlocationmanager')

**Comment by Lezh1k** [comment]
Try replace "compile" with "implementation". Maybe you have newest version of android studio and gradle . (compile is deprecated as I know)

**Comment by Lezh1k** [comment]
@Gabriel0402 any progress here? )))

**Comment by Gabriel0402** [comment]
tried implementation, still the same error here.

**Comment by Lezh1k** [comment]
What's your environment? I mean java version, studio version, OS etc. :) 
I just can't reproduce so I think it's somehow related to that stuff

**Comment by Gabriel0402** [comment]
I'm using java 8, 
Android Studio 3.1.3
Build #AI-173.4819257, built on June 4, 2018
JRE: 1.8.0_152-release-1024-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
and I tried both mac and windows 10, neither works.

**Comment by Lezh1k** [comment]
Ok, let me try to reproduce it on mac.

**Comment by Lezh1k** [comment]
can't reproduce.
