### ISSUE TITLE
Can the GeoHashRealTimeFilter be used with FusedLocationProvider

### ISSUE THREAD

**Issue by ebi-igweze** [maddevsio/mad-location-manager#27]
I will like to know if the geohash realtime filter can be used with the fused location provider from Google services.

I have tried using the kalmanService in this project, but when the car is in motion in high speed I can no longer read coordinates out of the GeoHash. I don't know if the GPS readings are failing completely, or the geohash real-time filter is not producing results. 

I am mostly using the defaults as is done in the current project, but still, I am unable to get updates, please let me know if any suggestions.

**Comment by Lezh1k** [comment]
Hello. 
Seems you need to change geohash precision, make it lower. 
Or disable it by setting minPointsCount to 1.
