### ISSUE TITLE
What if an Device has only accelerometer sensor like Moto G play any way to skip filtering and show route.

### ISSUE THREAD

**Issue by ashishkumawat** [maddevsio/mad-location-manager#34]

**Comment by Lezh1k** [comment]
Hello. 
You can use just geohash filter in this case.

**Comment by ashishkumawat** [comment]
Ok, I will check and try it.

**Comment by ashishkumawat** [comment]
After digging out in library have I to change 
`private Location locationAfterUpdateStep(SensorGpsDataItem sdi)
            {
}` 
This method convert SensorGpsDataItem object to location using Kalman filter.

**Comment by Lezh1k** [comment]
You can just use your GPS location manager (standard one) + RTGeoHashFilter.

**Comment by bcerquiare** [comment]
hei @ashishkumawat 
Could you tell me what you've changed?
I'm having the same problem
