### ISSUE TITLE
How i use Kalmanlocation inside my own service

### ISSUE THREAD

**Issue by mindfulritik** [maddevsio/mad-location-manager#36]
ServicesHelper.addLocationServiceInterface(SendLocation.this);
when I call this function oncreate of Service class then I get 
 
java.lang.ClassCastException: android.os.BinderProxy cannot be cast to mad.location.manager.lib.Services.KalmanLocationService$LocalBinder

Servicehelper lineno:67

**Comment by MosCriogen** [comment]
https://github.com/maddevsio/mad-location-manager/issues/29

the same - problem is in manifest

**Comment by MosCriogen** [comment]
find this string:   android:process=":service" in manifest 's section with  your service and copy to section with lib

**Comment by MosCriogen** [comment]
example:

my own service with calman lib calls
<service
        android:name="com.orderssupportapp.TestLocationUpdates"
        android:icon="@mipmap/ic_launcher"
        android:enabled="true"
        android:exported="true"
        android:launchMode="singleInstance"
        android:process=":service">
    </service> 

lib section:
   <service
        android:name="mad.location.manager.lib.Services.KalmanLocationService"

        android:process=":service"

        android:enabled="true"
        android:exported="false"
        android:stopWithTask="false" />

**Comment by Lezh1k** [comment]
@MosCriogen  thank you

**Comment by mindfulritik** [comment]
thank you @MosCriogen, now my problem solved .
