### ISSUE TITLE
Any ideas - how else to improve the track?

### ISSUE THREAD

**Issue by makarenkovov** [maddevsio/mad-location-manager#39]
Get rid of the stars finally?
![Screenshot_2019-03-19-14-10-07-188_com example lezh1k sensordatacollector](https://user-images.githubusercontent.com/48671789/54608435-1b81f000-4a6a-11e9-9030-94751c632257.png)
![Screenshot_2019-03-19-14-10-24-670_com example lezh1k sensordatacollector](https://user-images.githubusercontent.com/48671789/54608453-25a3ee80-4a6a-11e9-9898-5b542d899049.png)
Here such parameters were used:
public static final int GEOHASH_DEFAULT_PREC = 8;
public static final int GEOHASH_DEFAULT_MIN_POINT_COUNT = 3;

now added (while testing):
public static final int GPS_MIN_DISTANCE = 20;

**Comment by Lezh1k** [comment]
Try geohash precision = 7 and min point count = 3 :)

**Comment by makarenkovov** [comment]
Now trying geohash precision = 7 and min point count = 2

( it's wrong combination of settings (geohash - nothing remains for geohash )) ):
public static final int GEOHASH_DEFAULT_PREC = 8;
public static final int GEOHASH_DEFAULT_MIN_POINT_COUNT = 3;
public static final int GPS_MIN_DISTANCE = 20;)

**Comment by Lezh1k** [comment]
GPS_MIN_DISTANCE - this value for your gps receiver. 
GEOHASH_* - geohash settings. 
All these value should be provided into service (reset method).

**Comment by makarenkovov** [comment]
На русском изьяснюсь, чтобы понятнее было, что хотел сказать...
Да я все это понял - что для чего и куда. Мой предыдущий пост про то, что с такой настройкой геохешинг все отбросит, т.к. точки получаем через каждые 20 м, а геохешингом пытаемся отфильтровать 3 точки в радиусе 19 метров )) - что у меня и произошло)

**Comment by Lezh1k** [comment]
В этом случае да, геохэш всё отбросит. 
Вероятно в этом случае нужно взять геохэш с бОльшим радиусом, но тогда траектории становятся такими... более смазанными и усредненными. Можно отключить геохэш вообще, но тогда надо очень тщательно подобрать коэффициенты в матрицы шумов. Обычно для каждого телефона/транспорта разные.

**Comment by Lezh1k** [comment]
Закрываю, вроде вопрос исчерпан. Активности нет.

**Comment by makarenkovov** [comment]
I can add. To reduce the jump. It is necessary to leave only GPS in the settings of the phone source.
