### ISSUE TITLE
compiling Visualizer + disabling GeoHash

### ISSUE THREAD

**Issue by zobis2** [maddevsio/mad-location-manager#40]
heya , really nice project ! 
few questions  👍 
1. 
how do i compile the visualizer in order to play the log files(ubuntu or windows) ? i haven't found any Makefile in the project itself.
2.
 regarding GeoHash , if i want to disable it i just need to give 0,0 to his config under utils?
if so the green line on map will be only the raw GPS and the blue line will be the Correct GPS coordinate after kalman filter with corrected accelerometer  values at that time frame right?

my green and blue lines are on the same coordinates although ive tried to walk few mins in an open streen with the application .

thanks alot.

**Comment by Lezh1k** [comment]
Hello. Thank you for interest. 

1. It's qt-based project, so you need to use qmake. It's much better and more comfortable to use qtcreator. 
2. Yes, you need to set 0,0 .

**Comment by wurongfu1992** [comment]
Yes,my green and blue lines are on the same coordinates, I have try several times; It`s my phone sensor problem or I need change the configure？

**Comment by ReonLion** [comment]
> Yes,my green and blue lines are on the same coordinates, I have try several times; It`s my phone sensor problem or I need change the configure？

Hello, did you figure out what caused green and blue lines are on the same coordinates?

**Comment by wurongfu1992** [comment]
> > Yes,my green and blue lines are on the same coordinates, I have try several times; It`s my phone sensor problem or I need change the configure？
> 
> Hello, did you figure out what caused green and blue lines are on the same coordinates?

sry，I don't; I debug the original location info and kalman location info, find they are almost the same, except for accuracy.
