### ISSUE TITLE
Kalman throws simmilar results then gps

### ISSUE THREAD

**Issue by Sb8691** [maddevsio/mad-location-manager#43]
Hi, i'm not sure if this is an Issue with Library. When i implemented it with default settings and made few measurements i didnt saw any improvements in localization outcome. Maybe i'm doing something wrong but i set up the same Settings for only GPS sensor and the same with KalmanGPSsevice and the predicted results was almost the same then regular filter. Huawei pro 20 lite.

**Comment by Lezh1k** [comment]
If you have good GPS receiver and there are not high buildings and trees around results should be almost same.
