### ISSUE TITLE
matrixDestructiveInvert() question

### ISSUE THREAD

**Issue by liamrouly89** [maddevsio/mad-location-manager#46]
hello, 
Thanks for sharing this project and your work on it.

I have got a question about method to invert matrix. (matrixDestructiveInvert in Matrix class). 
I don't clearly understand the way how it is working. Could you tell me if there you use any specific algorithm or you can provide pseudo-code or any source where I can read more about the way you invert matrix in this method?

```
    public static boolean matrixDestructiveInvert(Matrix mtxin,
                                                  Matrix mtxout) {
       ...

            scalar = 1.0 / mtxin.data[r][r];
            mtxin.scaleRow(r, scalar);
            mtxout.scaleRow(r, scalar);

            for (ri = 0; ri < r; ++ri) {
                scalar = -mtxin.data[ri][r];
                mtxin.shearRow(ri, r, scalar);
                mtxout.shearRow(ri, r, scalar);
            }

            for (ri = r + 1; ri < mtxin.rows; ++ri) {
                scalar = -mtxin.data[ri][r];
                mtxin.shearRow(ri, r, scalar);
                mtxout.shearRow(ri, r, scalar);
            }
        } //for r < mtxin.rows
        return true;
    }
```

thank you in advance

**Comment by Lezh1k** [comment]
Hello. 
Honestly got it here : https://github.com/mydrive/ikalman/blob/master/matrix.c
