### ISSUE TITLE
Location bearing 

### ISSUE THREAD

**Issue by moti0375** [maddevsio/mad-location-manager#5]
Hi,

Thanks for this nice library. 
However, it seems that bearing isn't provided with Location callback. 
Could this issue be addressed ?

Thanks, 
Moti.

**Comment by Lezh1k** [comment]
Thanks for feedback, will be ready in 1-2 days.

**Comment by moti0375** [comment]
Thank you very much! 

Cheers, 
Moti.

**Comment by Lezh1k** [comment]
@moti0375 
Hello. Added bearing to master branch. Released :)

**Comment by Lezh1k** [comment]
@moti0375 
Finally released. Faced a lot of issues with new gradle/jitpack. And I'm not sure that it won't happened again. At least now you can use 0.1.11 version :) 
Thank you for waiting.

**Comment by Lezh1k** [comment]
Done.
