### ISSUE TITLE
GPS Status Disabled

### ISSUE THREAD

**Issue by moti0375** [maddevsio/mad-location-manager#6]
Hi,

From some reason, even when GPS is enabled, the GPSEnabledChanged callback initially gives a false status value followed by a true value. 

Thanks,
Moti.

**Comment by Lezh1k** [comment]
Sorry for late answer. 
Fix is on the way, today I'm going to release .

**Comment by moti0375** [comment]
Thanks you man!

Regards,
Moti.

**Comment by Lezh1k** [comment]
@moti0375 
Hello. Seem's like it's expected behavior. When service is started this callback should return true. When stopped - false (GPS should be enabled in settings).

**Comment by moti0375** [comment]
Hi Thanks, 

So you mean I should use: `ServicesHelper.addLocationServiceStatusInterface(mLocationServiceStatusInterface);` only after ` service.start()`

Something like this:

`KalmanLocationService.Settings settings = new KalmanLocationService.Settings(Utils.ACCELEROMETER_DEFAULT_DEVIATION,
                Utils.GPS_MIN_DISTANCE,
                interval,
                Utils.GEOHASH_DEFAULT_PREC,
                Utils.GEOHASH_DEFAULT_MIN_POINT_COUNT,
                Utils.SENSOR_DEFAULT_FREQ_HZ,
                this, false);

        service.reset(settings); //warning!! here you can adjust your filter behavior
        service.start(); 
        ServicesHelper.addLocationServiceStatusInterface(mLocationServiceStatusInterface);
`

OK

**Comment by Lezh1k** [comment]
Yes, you are right. :)
