### ISSUE TITLE
Sample data for the C module present

### ISSUE THREAD

**Issue by nazneenhuma** [maddevsio/mad-location-manager#64]
Hello,

I was trying to use the C module present in the package. I see that the module reads a file for the input value which is not part of the package. 
Can you provide example input file so that i can test it even without sensors in place.
Many thanks

**Comment by Lezh1k** [comment]
Hello.
Added sample data.
You will need to change path to file (sample_data_c/log1sorted) in main.cpp. 

Best regards, 
Oleg
