### ISSUE TITLE
using elapsedRealtimeNanos instead of elapsedRealtime

### ISSUE THREAD

**Issue by ftabashir** [maddevsio/mad-location-manager#80]
In `KalmanLocationService.onSensorChanged` current milliseconds is calculated like this:
```
long now = android.os.SystemClock.elapsedRealtimeNanos();
long nowMs = Utils.nano2milli(now);
```
Instead of `elapsedRealtimeNanos` and converting it to milliseconds you can directly use `SystemClock.elapsedRealtime`.
I wonder if using `long nowMs = SystemClock.elapsedRealtime()` had any issue which you avoid?

**Comment by Lezh1k** [comment]
No. I guess I didn't know about elapsedRealtime.
