### ISSUE TITLE
if I don’t use the LocationManager provided by Google to get real-time GPS information, what other data do I need to provide in order to use your wheels correctly

### ISSUE THREAD

**Issue by anyan131** [maddevsio/mad-location-manager#84]
First of all, thank you for your project.

The question I want to ask is, if I don’t use the LocationManager provided by Google to get real-time GPS information, what other data do I need to provide in order to use your wheels correctly

**Comment by Lezh1k** [comment]
Hello @anyan131 
Thank you for interest. 
If you don't use LocationManager - how do you receive Location data (GPS coordinates I mean)? Do you have any external GPS receiver or you want to use network data or something else?
