### ISSUE TITLE
jitpack dependency wrong

### ISSUE THREAD

**Issue by johannesneitzel** [maddevsio/mad-location-manager#92]
When following the jitpack link stated in your readme.md it gets you here: https://jitpack.io/#maddevsio/mad-location-manager
Now 

 	dependencies {
 	        implementation 'com.github.maddevsio:mad-location-manager:Tag'
 	}

didn't work for me. I had to state the dependency to your lib like this:

 	dependencies {
 	        implementation 'com.github.maddevsio:mad-location-manager:0.1.13'
 	}

In order to avoid compability issues it's good practise to explicitily state the version of the external dependency.

> Caution: When specifying dependencies, you should not use dynamic version numbers, such as 'com.android.tools.build:gradle:3.+'. Using this feature can cause unexpected version updates and difficulty resolving version differences.

https://developer.android.com/studio/build/dependencies

**Comment by Lezh1k** [comment]
@johannesneitzel 

Hello. Thank you. 
So  what do I need to change exactly? Maybe you can make pull request with these changes?

**Comment by johannesneitzel** [comment]
@Lezh1k 

Thanks for getting back to me! The problem was that I didn't click on: 
![grafik](https://user-images.githubusercontent.com/73041818/99103888-8c333400-25e0-11eb-875a-770ab6fa5a0f.png)

Which then will generate the correct link! Thus this isn't an issue.

**Comment by Lezh1k** [comment]
Ok, then I'll close this issue :)
