### ISSUE TITLE
how to calculate Deviation calculators ????

### ISSUE THREAD

**Issue by sakshi1357** [maddevsio/mad-location-manager#94]
After calculated the sigma value then how to relate to the deviation calculator ?? Please provide me a suitable explanation about it.

**Comment by Lezh1k** [comment]
Hello, @sakshi1357 
Thank you for interest in this project.

You need to lay your phone at some stable surface. Maybe some table or even floor. 
Then you need to collect accelerometer's values into some list or storage. 
After that you can calculate mean value and dispersion.
