### ISSUE TITLE
deviation calculators 

### ISSUE THREAD

**Issue by sakshi1357** [maddevsio/mad-location-manager#95]
After calculated the sigma value then how to relate to the deviation calculator ?? Please provide me a suitable explanation about it.

**Comment by Lezh1k** [comment]
@sakshi1357 
Seems like (here)[https://github.com/maddevsio/mad-location-manager/issues/94] I didn't get you. So. 
After you have calculated sigma you just need to set these values into observation noise matrix. R matrix. As I understand you need to set squared sigma there.
